# Generated by Django 5.1.7 on 2025-03-23 23:43

import accounts.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.TextField()),
                ("bot_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_1", models.CharField(blank=True, max_length=50, null=True)),
                ("address_2", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("United States", "United States"),
                            ("Canada", "Canada"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        null=True,
                        validators=[accounts.models.validate_phone_or_fax],
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        null=True,
                        validators=[accounts.models.validate_phone_or_fax],
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("contact_first", models.CharField(max_length=50)),
                ("contact_last", models.CharField(max_length=50)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select industry type"),
                            ("Agriculture", "Agriculture"),
                            ("Construction", "Construction"),
                            ("Education", "Education"),
                            ("Entertainment", "Entertainment"),
                            ("Finance & Insurance", "Finance &  Insurance"),
                            ("Healthcare", "Healthcare"),
                            ("Higher Education", "Higher  Education"),
                            ("Hospitality", "Hospitality"),
                            ("Information Technology", "Information  Technology"),
                            ("Manufacturing", "Manufacturing"),
                            ("Nonprofit", "Nonprofit"),
                            ("Professional Services", "Professional  Services"),
                            ("Real Estate", "Real  Estate"),
                            ("Retail", "Retail"),
                            ("Telecommunications", "Telecommunications"),
                            ("Transportation", "Transportation"),
                            ("Utilities", "Utilities"),
                            ("Wholesale", "Wholesale"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=150, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=150, unique=True)),
                (
                    "main_tech",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.technicianuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crm Companies",
            },
        ),
        migrations.CreateModel(
            name="ProjectList",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        default="Please add Project description... ",
                        null=True,
                    ),
                ),
                ("create_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "New"),
                            ("In Progress", "In Progress"),
                            ("Scheduled", "Scheduled"),
                            ("Follow Up", "Follow Up"),
                            ("Reviewing", "Reviewing"),
                            ("Observing", "Inprogress"),
                            ("Waiting on Client", "Waiting on Client"),
                            ("Waiting on Vendor", "Waiting on Vendor"),
                            ("Waiting on Client", "Waiting on Client"),
                            ("Postponed", "Postponed"),
                            ("Post to Call Waiting", "Post to Call Waiting"),
                            ("Completed", "Completed"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Emergency", "Emergency"),
                            ("High", "High"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("assignment", models.ManyToManyField(to="accounts.technicianuser")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_app.clientcompany",
                    ),
                ),
            ],
            options={
                "ordering": ["-name"],
                "permissions": [
                    ("view_own_projects", "Can view their own projects"),
                    ("assign_own_project", "Can assign themselves to a project"),
                    ("assign_other_project", "Can assign others to a project"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketList",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, default="Add description for Ticket: ", null=True
                    ),
                ),
                ("create_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In Progress", "In Progress"),
                            ("Scheduled", "Scheduled"),
                            ("Postponed", "Postponed"),
                            ("Waiting on Client", "Waiting on Client"),
                            ("Waiting on Vendor", "Waiting on Vendor"),
                            ("Follow-Up", "Follow-Up"),
                            ("Need to Post", "Need to Post"),
                            ("Completed", "Completed"),
                            ("Closed", "Closed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Emergency", "Emergency"),
                            ("High", "High"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("assignment", models.ManyToManyField(to="accounts.technicianuser")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_app.clientcompany",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_app.projectlist",
                    ),
                ),
            ],
            options={
                "ordering": ["-identifier"],
                "permissions": [
                    ("view_own_tickets", "Can view own tickets"),
                    ("view_ticket_stats", "Can view ticket statistics"),
                    ("view_estimated_work", "Can view estimated work"),
                    ("assign_own_ticket", "Can assign themselves to a ticket"),
                    ("assign_other_ticket", "Can assign others to a ticket"),
                    ("complete_ticket", "Can mark a ticket as Completed"),
                    ("close_ticket", "Can mark a ticket as Closed"),
                ],
            },
        ),
    ]
