# Generated by Django 5.1.7 on 2025-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlist',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
