# Generated by Django 4.2.13 on 2025-03-22 12:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot_app", "0002_user_rename_created_at_chathistory_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketList",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, default="Add description for Ticket: ", null=True
                    ),
                ),
                ("create_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In Progress", "In Progress"),
                            ("Scheduled", "Scheduled"),
                            ("Postponed", "Postponed"),
                            ("Waiting on Client", "Waiting on Client"),
                            ("Waiting on Vendor", "Waiting on Vendor"),
                            ("Follow-Up", "Follow-Up"),
                            ("Need to Post", "Need to Post"),
                            ("Completed", "Completed"),
                            ("Closed", "Closed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Emergency", "Emergency"),
                            ("High", "High"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-identifier"],
                "permissions": [
                    ("view_own_tickets", "Can view own tickets"),
                    ("view_ticket_stats", "Can view ticket statistics"),
                    ("view_estimated_work", "Can view estimated work"),
                    ("assign_own_ticket", "Can assign themselves to a ticket"),
                    ("assign_other_ticket", "Can assign others to a ticket"),
                    ("complete_ticket", "Can mark a ticket as Completed"),
                    ("close_ticket", "Can mark a ticket as Closed"),
                ],
            },
        ),
    ]
